CREATE INDEX flight_id_ind ON flights USING hash(flight_id);
CREATE INDEX flight_id_amount_ind ON ticket_flights(flight_id, amount);
CREATE INDEX aircraft_code_ind ON flights(aircraft_code, departure_airport, arrival_airport);
CREATE INDEX flight_no_arr_ind ON flights(arrival_airport, flight_no);
CREATE INDEX flight_no_dep_ind ON flights(departure_airport, flight_no);
CREATE INDEX passenger_id_ind ON tickets USING hash(passenger_id);
CREATE INDEX bp_ticket_no_ind ON boarding_passes USING hash(ticket_no);
CREATE INDEX departure_ind ON flights(departure_airport, scheduled_departure);
CREATE INDEX aircraft_ind ON flights(aircraft_code);
CREATE INDEX flight_id_ticket_no_ind ON ticket_flights(flight_id, ticket_no);
CREATE INDEX ticket_no_ind ON tickets USING hash(ticket_no);
CREATE INDEX act_arr_sched_dep_ind ON flights(aircraft_code, actual_arrival, scheduled_departure);
CREATE INDEX act_dep_sched_arr_ind ON flights(aircraft_code, actual_departure, scheduled_arrival);
CREATE INDEX aircraft_code_flight_id_ind ON flights(aircraft_code, flight_id);
CREATE INDEX aircraft_code_dep_airport_ind ON flights(aircraft_code, departure_airport);
CREATE INDEX aircraft_code_model_ind ON aircrafts_data(aircraft_code, model);
CREATE INDEX flight_id_amount_ind2 ON ticket_flights(flight_id, amount);
CREATE INDEX flight_id_ticket_no_ind2 ON ticket_flights(flight_id, ticket_no);
CREATE INDEX book_ref_ind ON bookings USING hash(book_ref);
CREATE INDEX book_ref_ind2 ON tickets USING hash(book_ref);
CREATE INDEX ticket_no_ind2 ON boarding_passes(ticket_no);
CREATE INDEX amount_ind ON ticket_flights(amount);
CREATE INDEX book_ref_ticket_no_ind ON tickets(book_ref, ticket_no);
CREATE INDEX arrival_airport_ind ON flights(arrival_airport);
CREATE INDEX departure_airport_ind ON flights(departure_airport);
CREATE INDEX ind ON tickets(ticket_no, passenger_name, passenger_id);
